[package]
name = "quark-db"
version = "0.1.0"
authors = ["lightclient@protonmail.com <lightclient@protonmail.com>"]
edition = "2018"

[dependencies]
quark-common = { path = "../quark-common" }
quark-types = { path = "../quark-types" }
